// Overdose Good Samaritan laws by jurisdiction, shown during onboarding. This is general
// information, not legal advice: protections are narrow, conditional and change over time.
//
// Sources (reviewed 2026-10-04): Network for Public Health Law, "Legal Interventions to Reduce
// Overdose Mortality: Overdose Good Samaritan Laws" (50-state survey, Dec. 31, 2025, which reports
// all 50 states and DC have such a law, Wyoming last in 2025); LAPPA, "Good Samaritan Fatal
// Overdose Prevention and Drug-Induced Homicide" (Aug. 2025); and state legislature summaries
// (e.g. Kansas House Sub. for SB 419 (2024), Texas HB 1694 (2021), Wyoming SF0074 (2025)).
// Summaries are deliberately conservative. Re-verify before changing any entry; record the date.

export const GOOD_SAMARITAN_LAWS_REVIEWED = "2026-10-04"

export const GOOD_SAMARITAN_SOURCES = [
  {
    title: "Network for Public Health Law: Overdose Good Samaritan Laws (50-state survey)",
    url: "https://www.networkforphl.org/resources/legal-interventions-to-reduce-overdose-mortality-overdose-good-samaritan-laws/",
  },
  {
    title: "LAPPA: Good Samaritan Fatal Overdose Prevention laws",
    url: "https://legislativeanalysis.org/wp-content/uploads/2025/08/Good-Samaritan-Fatal-Overdose-Prevention-and-Drug-Induced-Homidice.pdf",
  },
] as const

export interface GoodSamaritanLaw {
  /** Jurisdiction name exactly as offered in the onboarding state picker. */
  name: string
  citation: string
  /** Plain-language scope: who is covered and from what. */
  summary: string
  /** Conditions or gaps a person should know about, when known. */
  limits?: string
}

export const GOOD_SAMARITAN_LAWS: readonly GoodSamaritanLaw[] = [
  { name: "Alabama", citation: "Ala. Code § 20-2-281", summary: "A person who seeks medical help for someone else's overdose may not be prosecuted for a misdemeanor controlled-substance offense discovered only because they sought help." },
  { name: "Alaska", citation: "Alaska Stat. § 11.71.311", summary: "A person who in good faith seeks medical or law-enforcement help for someone they believe is overdosing may not be prosecuted for certain drug-possession offenses found only because of that call.", limits: "Requires staying at the scene and cooperating with responders." },
  { name: "Arizona", citation: "Ariz. Rev. Stat. § 13-3423", summary: "The person who seeks help in good faith and the person who overdosed may not be charged or prosecuted for possession or use of a controlled substance or paraphernalia when the evidence comes only from the call for help." },
  { name: "Arkansas", citation: "Ark. Code Ann. § 20-13-1704", summary: "A person who seeks medical help for an overdose is protected from arrest, charge and prosecution for possession of a controlled substance or paraphernalia found because they sought help." },
  { name: "California", citation: "Cal. Health & Safety Code § 11376.5", summary: "The person who seeks help in good faith and the person who overdosed are protected from charges for being under the influence or possessing a controlled substance or paraphernalia for personal use, when the evidence comes from seeking help." },
  { name: "Colorado", citation: "Colo. Rev. Stat. § 18-1-711", summary: "A person who reports a drug or alcohol overdose in good faith to 911, law enforcement or a medical provider, and the person who overdosed, are immune from prosecution for listed possession and paraphernalia offenses." },
  { name: "Connecticut", citation: "Conn. Gen. Stat. § 21a-279(d)", summary: "The person who calls for help and the person who overdosed are protected from arrest, charge and prosecution for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Delaware", citation: "Del. Code Ann. tit. 16, § 4769", summary: "The person experiencing an overdose or other life-threatening emergency, and anyone seeking medical help for them, may not be arrested, charged or prosecuted for possession of a controlled substance or paraphernalia, or underage alcohol offenses, found because help was sought." },
  { name: "District of Columbia", citation: "D.C. Code § 7-403", summary: "A person who seeks help for a drug or alcohol overdose, including the person experiencing it, may not be charged, prosecuted or penalized for possession of a controlled substance or paraphernalia found as a result." },
  { name: "Florida", citation: "Fla. Stat. § 893.21", summary: "A person who seeks medical help in good faith for someone's overdose, and the person who overdosed, may not be charged, prosecuted or penalized for possession of a controlled substance found because help was sought." },
  { name: "Georgia", citation: "Ga. Code Ann. § 16-13-5", summary: "A person who in good faith seeks medical help for an overdose, and the person who overdosed, may not be arrested, charged or prosecuted for certain drug-possession or paraphernalia offenses when the only evidence comes from seeking help.", limits: "Covers small amounts only." },
  { name: "Hawaii", citation: "Haw. Rev. Stat. § 329-43.6", summary: "A person who in good faith seeks medical help for a drug or alcohol overdose may not be arrested, charged or prosecuted for covered possession and paraphernalia offenses when the only evidence comes from seeking help." },
  { name: "Idaho", citation: "Idaho Code § 37-2739C", summary: "The person who seeks help and the person who overdosed are protected from charge and prosecution, but not arrest, for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Illinois", citation: "720 Ill. Comp. Stat. 570/414", summary: "The person who seeks help and the person who overdosed are protected from charge and prosecution for possession of small amounts of a controlled substance found because help was sought." },
  { name: "Indiana", citation: "Ind. Code § 16-42-27-2", summary: "A person who calls for emergency help for someone appearing to have an opioid overdose may be immune from possession charges only if they also administered naloxone, gave their full name, stayed until help arrived and cooperated.", limits: "Narrow: the conditions above must all be met. Indiana courts may also treat seeking help as a mitigating factor at sentencing (Ind. Code § 35-38-1-7.1)." },
  { name: "Iowa", citation: "Iowa Code § 124.418", summary: "A person who seeks help for an overdose is protected from prosecution for possession of a controlled substance or paraphernalia found because help was sought.", limits: "The protection can be used only once by the person who reports." },
  { name: "Kansas", citation: "2024 Kan. Sess. Laws ch. 97 (House Sub. for SB 419)", summary: "A person who seeks medical help for a drug-related emergency, for themselves or another person, is immune from prosecution for possession of a controlled substance or certain paraphernalia found because help was sought.", limits: "Requires cooperating with law enforcement and EMS. People on probation or parole were not given protection from violations." },
  { name: "Kentucky", citation: "Ky. Rev. Stat. § 218A.133", summary: "A person who seeks help for an overdose, and the person who overdosed, are protected from charge and prosecution, but not arrest, for possession of a controlled substance or paraphernalia." },
  { name: "Louisiana", citation: "La. Rev. Stat. § 14:403.10", summary: "A person who seeks medical help for an overdose, and the person who overdosed, may not be charged or prosecuted for possession of a controlled substance found because help was sought." },
  { name: "Maine", citation: "Me. Rev. Stat. tit. 17-A, § 1111-B", summary: "Since 2022, the person who calls, people rendering aid at the scene and the person who overdosed are generally protected from arrest and prosecution for possession of drugs or paraphernalia." },
  { name: "Maryland", citation: "Md. Code, Crim. Proc. § 1-210", summary: "A person who seeks medical help for someone experiencing a medical emergency after drug or alcohol use, and the person experiencing it, may not be arrested, charged or prosecuted for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Massachusetts", citation: "Mass. Gen. Laws ch. 94C, § 34A", summary: "A person who seeks medical help in good faith for an overdose, and the person who overdosed, may not be charged or prosecuted for possession of a controlled substance found because help was sought." },
  { name: "Michigan", citation: "Mich. Comp. Laws § 333.7404(3)", summary: "A person who seeks medical help for someone's overdose, and in some cases the person who overdosed, is protected from prosecution for use or possession of a controlled substance found because help was sought." },
  { name: "Minnesota", citation: "Minn. Stat. § 604A.05", summary: "A person acting in good faith who seeks medical help for someone's drug-related overdose, and the person who overdosed, may not be charged or prosecuted for possession, sharing or use of a controlled substance or paraphernalia." },
  { name: "Mississippi", citation: "Miss. Code Ann. § 41-29-149.1", summary: "The person who calls for help, people who assist them and the person who overdosed are protected from charge and prosecution for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Missouri", citation: "Mo. Rev. Stat. § 195.205", summary: "The person who seeks help in good faith and the person who overdosed may not be arrested, charged or prosecuted for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Montana", citation: "Mont. Code Ann. § 50-32-609", summary: "The person who calls for help, people who assist and the person who overdosed are protected from charge and prosecution for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Nebraska", citation: "Neb. Rev. Stat. § 28-472", summary: "The person who seeks help in good faith and the person who overdosed are protected from charge and prosecution for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Nevada", citation: "Nev. Rev. Stat. § 453C.150", summary: "A person who seeks medical help for an overdose, and the person who overdosed, may not be arrested, charged, prosecuted or convicted for using or possessing a controlled substance or paraphernalia found because help was sought.", limits: "Excludes some substances and amounts, and possession with intent to sell." },
  { name: "New Hampshire", citation: "N.H. Rev. Stat. § 318-B:28-b", summary: "A person who seeks medical help for an overdose, and the person who overdosed, may not be arrested, charged or prosecuted for possession of a controlled substance found because help was sought.", limits: "Does not cover possession with intent to sell." },
  { name: "New Jersey", citation: "N.J. Stat. § 2C:35-30", summary: "A person who seeks medical help for an overdose may not be arrested, charged, prosecuted or convicted for using or possessing a controlled substance or paraphernalia found because help was sought; § 2C:35-31 extends this to the person who overdosed." },
  { name: "New Mexico", citation: "N.M. Stat. § 30-31-27.1", summary: "A person who in good faith seeks medical help for a drug or alcohol overdose, and the person who overdosed, may not be arrested, charged, prosecuted or otherwise penalized for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "New York", citation: "N.Y. Penal Law § 220.78", summary: "A person who in good faith seeks health care for someone's drug or alcohol overdose or other life-threatening emergency, and the person experiencing it, may not be charged or prosecuted for covered possession offenses when the evidence comes from seeking care.", limits: "Does not cover sale offenses, some larger amounts, or unrelated crimes." },
  { name: "North Carolina", citation: "N.C. Gen. Stat. § 90-96.2", summary: "A person who in good faith calls for help for someone's drug-related overdose, and the person who overdosed, may not be prosecuted for certain controlled-substance possession and paraphernalia offenses found because help was sought.", limits: "The caller must reasonably believe they were the first to call and give their name to responders." },
  { name: "North Dakota", citation: "N.D. Cent. Code § 19-03.1-23.4", summary: "Up to three people, including the person who overdosed, are protected from prosecution for ingestion or possession of a controlled substance or paraphernalia when help is sought.", limits: "Requires staying at the scene and cooperating." },
  { name: "Ohio", citation: "Ohio Rev. Code § 2925.11(B)(2)", summary: "A person who seeks help for an overdose, for themselves or another person, may be immune from minor drug-possession charges (misdemeanor or fifth-degree felony amounts).", limits: "Requires getting a screening and referral for treatment within 30 days, and cannot be used more than twice." },
  { name: "Oklahoma", citation: "Okla. Stat. tit. 63, § 2-413.1", summary: "A person who seeks medical help for an overdose is protected from arrest, charge and prosecution for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Oregon", citation: "Or. Rev. Stat. § 475.898", summary: "The person who seeks help, people who assist, and the person who overdosed may not be arrested or prosecuted for possession of a controlled substance or paraphernalia found because help was sought, and are protected from certain probation or parole violations." },
  { name: "Pennsylvania", citation: "35 Pa. Stat. § 780-113.7", summary: "A person who reports an overdose is protected from charge and prosecution, but not arrest, for possession of a controlled substance or paraphernalia found because they sought help.", limits: "The person who overdosed is protected only if the caller qualifies; the caller must give their name and stay with the person." },
  { name: "Rhode Island", citation: "R.I. Gen. Laws § 21-28.9-4", summary: "A person who seeks medical help in good faith for an overdose, and the person who overdosed, may not be charged or prosecuted for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "South Carolina", citation: "S.C. Code Ann. § 44-53-1920", summary: "A person who seeks medical help for an overdose, and the person who overdosed, may not be prosecuted for possession of small amounts of a controlled substance or paraphernalia found because help was sought.", limits: "Courts may consider past times the person sought help." },
  { name: "South Dakota", citation: "S.D. Codified Laws §§ 34-20A-109 to 34-20A-113", summary: "A person who calls for help for someone's drug-related overdose, and the person who overdosed, may not be arrested, charged or prosecuted for possessing or ingesting a controlled substance found because help was sought." },
  { name: "Tennessee", citation: "Tenn. Code Ann. § 63-1-156", summary: "A person who in good faith seeks medical help for someone's drug overdose, and the person who overdosed, are immune from arrest, charge or prosecution for possession of small amounts of a controlled substance or paraphernalia.", limits: "Limits apply to a person with a prior overdose on record." },
  { name: "Texas", citation: "Tex. Health & Safety Code § 481.115(g) (Jessica Sosa Act, 2021)", summary: "Texas gives a defense in court, not immunity from arrest: the first person to call for emergency help for someone else's overdose, and the person who overdosed, can raise it against charges for possessing small amounts.", limits: "Not available if police were already arresting or searching, or if the person requested overdose help in the previous 18 months. The caller must stay and cooperate." },
  { name: "Utah", citation: "Utah Code § 58-37-8(16)", summary: "Utah gives an affirmative defense in court, not immunity: a person who reports an overdose in good faith can raise it against covered drug-possession charges. Seeking help can also reduce a sentence (Utah Code § 76-3-203.11).", limits: "Requires staying at the scene and cooperating." },
  { name: "Vermont", citation: "Vt. Stat. tit. 18, § 4254", summary: "A person who seeks medical help for someone's drug overdose, and the person who overdosed, may not be cited, arrested or prosecuted for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Virginia", citation: "Va. Code § 18.2-251.03", summary: "Since 2020, a person who in good faith seeks or provides emergency help for an overdose, and the person who overdosed, may not be arrested or prosecuted for covered drug possession, paraphernalia or public intoxication offenses.", limits: "Requires staying at the scene, identifying yourself and cooperating." },
  { name: "Washington", citation: "Rev. Code Wash. § 69.50.315", summary: "A person who seeks medical help in good faith for someone's drug-related overdose, and the person who overdosed, may not be charged or prosecuted for possession of a controlled substance found because help was sought." },
  { name: "West Virginia", citation: "W. Va. Code § 16-47-4", summary: "A person who seeks medical help for someone they reasonably believe is overdosing is protected from criminal responsibility for possession of a controlled substance, underage drinking or public intoxication found because help was sought.", limits: "Requires staying with the person until help arrives and identifying yourself if asked." },
  { name: "Wisconsin", citation: "Wis. Stat. § 961.443", summary: "A person who seeks help for someone's overdose, and since 2021 the person who overdosed, are immune from prosecution for possession of a controlled substance or paraphernalia found because help was sought." },
  { name: "Wyoming", citation: "Wyo. Stat. § 35-7-1064 (2025 SF0074)", summary: "A person who in good faith seeks help for a drug overdose, for themselves or another person, may not be arrested, charged or prosecuted for possession of a controlled substance found because help was sought.", limits: "Available at most twice in 12 months; the second time requires agreeing to an approved treatment program." },
]

export function goodSamaritanLawFor(name: string | undefined): GoodSamaritanLaw | undefined {
  if (!name) return undefined
  return GOOD_SAMARITAN_LAWS.find((law) => law.name === name)
}
