-- NarcoGuard baseline schema for Supabase Postgres.
-- Apply with: supabase db push (or paste into the Supabase SQL editor).

create table if not exists users (
  id bigint generated by default as identity primary key,
  display_name text not null,
  email text not null unique,
  phone text,
  role text not null default 'user',
  avatar_url text,
  is_active boolean not null default true,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists vitals_readings (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  heart_rate integer not null,
  spo2 numeric(5,2) not null,
  respiratory_rate integer not null,
  skin_temperature numeric(6,2),
  blood_pressure_systolic integer,
  blood_pressure_diastolic integer,
  motion_level text not null default 'normal',
  risk_level text not null,
  recorded_at timestamptz not null default now()
);

create table if not exists emergencies (
  id bigint generated by default as identity primary key,
  emergency_id text not null unique,
  user_id bigint references users(id) on delete set null,
  latitude numeric(10,7) not null,
  longitude numeric(10,7) not null,
  address text,
  emergency_type text not null default 'overdose',
  status text not null default 'active' check (status in ('active','responding','resolved','cancelled')),
  vitals_at_trigger jsonb not null default '{}'::jsonb,
  auto_injection_triggered boolean not null default false,
  naloxone_deployed boolean not null default false,
  response_time_seconds integer,
  notes text,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists heroes (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  is_certified boolean not null default false,
  narcan_trained boolean not null default false,
  cpr_trained boolean not null default false,
  carries_naloxone boolean not null default false,
  availability_status text not null default 'available' check (availability_status in ('available','busy','offline')),
  response_radius_miles numeric(8,2) not null default 5,
  total_responses integer not null default 0,
  certification_date date,
  last_active_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists emergency_responses (
  id bigint generated by default as identity primary key,
  emergency_id bigint not null references emergencies(id) on delete cascade,
  hero_id bigint not null references heroes(id) on delete cascade,
  status text not null default 'dispatched' check (status in ('dispatched','en_route','on_scene','completed','cancelled')),
  eta_seconds integer,
  distance_miles numeric(8,2),
  arrived_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists locations (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  latitude numeric(10,7) not null,
  longitude numeric(10,7) not null,
  accuracy numeric(8,2),
  altitude numeric(8,2),
  speed numeric(8,2),
  heading numeric(8,2),
  recorded_at timestamptz not null default now()
);

create table if not exists watches (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  serial_number text not null unique,
  firmware_version text not null default '1.0.0',
  battery_level integer,
  is_connected boolean not null default false,
  naloxone_cartridge_status text not null default 'loaded',
  naloxone_expiry_date date,
  last_sync_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists donations (
  id bigint generated by default as identity primary key,
  donor_name text not null default 'Anonymous',
  donor_email text,
  amount numeric(12,2) not null check (amount >= 0),
  source text not null default 'gofundme',
  message text,
  is_anonymous boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists activity_log (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  ip_address inet,
  created_at timestamptz not null default now()
);

create table if not exists legal_agreements (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  agreement_type text not null,
  ip_address inet,
  agreed_at timestamptz not null default now()
);

create table if not exists emergency_contacts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  name text not null,
  phone text not null,
  relationship text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists vitals_user_recorded_idx on vitals_readings(user_id, recorded_at desc);
create index if not exists emergencies_status_created_idx on emergencies(status, created_at desc);
create index if not exists heroes_availability_idx on heroes(availability_status, last_active_at desc);
create index if not exists locations_user_recorded_idx on locations(user_id, recorded_at desc);
create index if not exists activity_created_idx on activity_log(created_at desc);

create or replace function set_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on users;
create trigger users_set_updated_at before update on users for each row execute function set_updated_at();
